#!/bin/bash

function copySSH() {
    local USER="$1"
    local DOMAIN="$2"
    scp -o StrictHostKeyChecking=no -A "$3" "$USER@$DOMAIN":"$4" 2>&1
    return $?
}

function execSSH() {
    local USER="$1"
    local DOMAIN="$2"
    local COMMAND="$3"
    ssh -o LogLevel=QUIET -o StrictHostKeyChecking=accept-new -tA "$USER"@"$DOMAIN" -- "$COMMAND"
    return $?
}

function createDeploymentZip() {
    local ENV="$1"
    local BRANCH="$2"
    local DEPLOYMENT
    DEPLOYMENT=$(date +"%Y%m%d%H%M%S")

    if [[ -z "$BRANCH" ]]; then
        BRANCH=$(input -n -p "branch")
    fi

    mkdir "$PROJECT_DIR/deployments/$DEPLOYMENT"

    # Fetch latest remote state to ensure we have the most current version of the branch/tag
    info "Fetching latest remote state for deployment..."
    git -C "$PROJECT_DIR"/htdocs fetch --all --tags

    # create worktree
    git -C "$PROJECT_DIR"/htdocs worktree add --detach "$PROJECT_DIR/deployments/$DEPLOYMENT" "$BRANCH"

    # shellcheck disable=SC2034
    local BASE_DOMAIN
    # shellcheck disable=SC2034
    local ENVIRONMENT
    # shellcheck disable=SC2034
    local DB_HOST_PORT
    local PHP_VERSION
    # shellcheck disable=SC2034
    local PROJECTNAME
    # shellcheck disable=SC2034
    local XDEBUG_IP
    # shellcheck disable=SC2034
    local IDE_KEY
    . "$PROJECT_DIR"/.env
    docker run \
        -u "$(id -u):$(id -g)" \
        --group-add www-data \
        -e SSH_AUTH_PORT="$SSH_AUTH_PORT" \
        -e SSH_AUTH_SOCK=/tmp/ssh-agent.sock \
        --add-host "host.docker.internal:host-gateway" \
        -v "$PROJECT_DIR/volumes/composer-cache:/var/www/.composer/cache" \
        -v "$PROJECT_DIR/deployments/$DEPLOYMENT":/var/www/html fduarte42/docker-php:"$PHP_VERSION" \
        bash -c "/docker-php-init; composer i -o"

    if [[ $(type -t "pre_deploy_encode_hook_$ENV") == "function" ]]; then
        DEPLOYMENT=$("pre_deploy_encode_hook_$ENV" "$ENV" "$BRANCH" "$DEPLOYMENT")
    fi

    cd "$PROJECT_DIR/deployments/$DEPLOYMENT" || fatal "could not change directory into $PROJECT_DIR/deployments/$DEPLOYMENT"
    7z a "$PROJECT_DIR/deployments/$DEPLOYMENT.7z" ./*
    cd "$PROJECT_DIR" || fatal "could not change directory into $PROJECT_DIR"

    # remove worktree
    git -C "$PROJECT_DIR"/htdocs worktree remove "$PROJECT_DIR"/deployments/"$DEPLOYMENT" --force

    echo "$PROJECT_DIR/deployments/$DEPLOYMENT.7z"
}

function createDeploymentHooks() {
    local ENV="$1"
    local DEPLOYMENT_SCRIPTS_DIR

    # Check for .docker-control directory first, fallback to legacy location
    if [[ -d "$PROJECT_DIR/htdocs/.docker-control/deployment-scripts" ]]; then
        DEPLOYMENT_SCRIPTS_DIR="$PROJECT_DIR/htdocs/.docker-control/deployment-scripts"
        # Ensure the directory is accessible
        if [[ ! -w "$DEPLOYMENT_SCRIPTS_DIR" ]]; then
            critical "Directory $DEPLOYMENT_SCRIPTS_DIR exists but is not writable"
            exit 1
        fi
    else
        DEPLOYMENT_SCRIPTS_DIR="$PROJECT_DIR/deployments/scripts"
        # Create legacy directory if it doesn't exist
        if ! mkdir -p "$DEPLOYMENT_SCRIPTS_DIR"; then
            critical "Failed to create deployment scripts directory: $DEPLOYMENT_SCRIPTS_DIR"
            exit 1
        fi
    fi

    if [[ -f "$DEPLOYMENT_SCRIPTS_DIR/$ENV.sh" ]]; then
        critical "deployment hook for $ENV already created at $DEPLOYMENT_SCRIPTS_DIR/$ENV.sh"
        exit 1
    fi

    cat << EOF | tee "$DEPLOYMENT_SCRIPTS_DIR/${ENV}.sh" 1>/dev/null
#!/bin/bash
set -e

. "\$LIB_DIR/util-functions.sh"

# This file was autogenerated. Feel free to edit it, but do not change the function names.
# If a hook is not needed, you can simply remove the function

function pre_deploy_encode_hook_$ENV() {
    local ENV="\$1"
    local BRANCH="\$2"
    local DEPLOYMENT="\$3"
    local DEPLOYMENT_ENCODED="\${DEPLOYMENT}_encoded"

    # add encoding here
    # encoded files need to be in \$DEPLOYMENT_ENCODED directory
    # deployment directories are relative to \$PROJECT_DIR/deployments

    # change this output to \$DEPLOYMENT_ENCODED after implementation
    echo "\$DEPLOYMENT"
}

function pre_deploy_hook_$ENV() {
    local USER="\$1"
    local DOMAIN="\$2"
    local SERVER_ROOT="\$3"
    local DEPLOYMENT_DIRECTORY="\$4"
    local CONSOLE_PATH_NEW_RELEASE="\$5"

    # this hook runs after maintenance is enabled on the server
    # you can execute scripts on the server via:
    #   execSSH "\$USER" "\$DOMAIN" "<COMMAND>"
    # to execute console commands for the new release use:
    #   execSSH "\$USER" "\$DOMAIN" "\$CONSOLE_PATH_NEW_RELEASE <COMMAND>"

}

function post_deploy_hook_$ENV() {
    local USER="\$1"
    local DOMAIN="\$2"
    local SERVER_ROOT="\$3"
    local DEPLOYMENT_DIRECTORY="\$4"
    local CONSOLE_PATH_NEW_RELEASE="\$5"

    # this hook runs after deployment is done, before disabling maintenance
    # you can execute scripts on the server via:
    #   execSSH "\$USER" "\$DOMAIN" "<COMMAND>"
    # to execute console commands for the new release use:
    #   execSSH "\$USER" "\$DOMAIN" "\$CONSOLE_PATH_NEW_RELEASE <COMMAND>"
}

function done_deploy_hook_$ENV() {
    local USER="\$1"
    local DOMAIN="\$2"
    local SERVER_ROOT="\$3"
    local DEPLOYMENT_DIRECTORY="\$4"
    local CONSOLE_PATH_NEW_RELEASE="\$5"

    # this hook runs after deployment is done, before disabling maintenance
    # you can execute scripts on the server via:
    #   execSSH "\$USER" "\$DOMAIN" "<COMMAND>"
    # to execute console commands for the new release use:
    #   execSSH "\$USER" "\$DOMAIN" "\$CONSOLE_PATH_NEW_RELEASE <COMMAND>"
}

exit 0
EOF

}

function deploy() {
    local ENV="$1"
    local USER="$2"
    local DOMAIN="$3"
    local SERVER_ROOT="${4:-/var/www/html}"
    local BRANCH="$5"

    local DEPLOYMENT
    DEPLOYMENT=$(createDeploymentZip "$BRANCH")
    local DEPLOYMENT_FILENAME
    DEPLOYMENT_FILENAME=$(basename "$DEPLOYMENT")
    local DEPLOYMENT_DIRECTORY
    DEPLOYMENT_DIRECTORY=$(basename "$DEPLOYMENT" .7z)

    # Check for deployment scripts in .docker-control directory first, then fallback to legacy location
    local DEPLOYMENT_SCRIPT_PATH=""
    if [[ -f "$PROJECT_DIR/htdocs/.docker-control/deployment-scripts/$ENV.sh" ]] && [[ -r "$PROJECT_DIR/htdocs/.docker-control/deployment-scripts/$ENV.sh" ]]; then
        DEPLOYMENT_SCRIPT_PATH="$PROJECT_DIR/htdocs/.docker-control/deployment-scripts/$ENV.sh"
    elif [[ -f "$PROJECT_DIR/deployments/scripts/$ENV.sh" ]] && [[ -r "$PROJECT_DIR/deployments/scripts/$ENV.sh" ]]; then
        DEPLOYMENT_SCRIPT_PATH="$PROJECT_DIR/deployments/scripts/$ENV.sh"
    else
        # Create deployment hooks if none exist
        createDeploymentHooks "$ENV"
        # After creation, determine the path again
        if [[ -d "$PROJECT_DIR/htdocs/.docker-control/deployment-scripts" ]]; then
            DEPLOYMENT_SCRIPT_PATH="$PROJECT_DIR/htdocs/.docker-control/deployment-scripts/$ENV.sh"
        else
            DEPLOYMENT_SCRIPT_PATH="$PROJECT_DIR/deployments/scripts/$ENV.sh"
        fi

        # Verify the created script is readable
        if [[ ! -r "$DEPLOYMENT_SCRIPT_PATH" ]]; then
            critical "Created deployment script $DEPLOYMENT_SCRIPT_PATH is not readable"
            exit 1
        fi
    fi

    # shellcheck disable=SC1090
    . "$DEPLOYMENT_SCRIPT_PATH"

    # copy deployment file to server
    copySSH "$USER" "$DOMAIN" "$DEPLOYMENT" "$SERVER_ROOT/releases/$DEPLOYMENT_FILENAME"

    # extract deployment file and remove it
    execSSH "$USER" "$DOMAIN" "mkdir $SERVER_ROOT/releases/$DEPLOYMENT_DIRECTORY"
    execSSH "$USER" "$DOMAIN" "7z x -o$SERVER_ROOT/releases/$DEPLOYMENT_DIRECTORY $SERVER_ROOT/releases/$DEPLOYMENT_FILENAME"
    execSSH "$USER" "$DOMAIN" "rm -f $SERVER_ROOT/releases/$DEPLOYMENT_FILENAME"

    # remove old deployments
    execSSH "$USER" "$DOMAIN" "bash -c 'ls -d1t $SERVER_ROOT/releases/* | grep -v \$(readlink -f $SERVER_ROOT/current) | egrep \"^$SERVER_ROOT/releases/[0-9]{14}_.+\$\" | tail -n +6 | xargs rm -rf'"

    if [[ "$(confirm -n "Unpacking finished, continue?")" == "n" ]]; then
        critical "deployment canceled"
        exit 1
    fi

    info "Reloading FPM"
    execSSH "$USER" "$DOMAIN" "sudo php-fpm-reload.sh"


    # register deployment consoles
    local CONSOLE_PATH_CURRENT="php $SERVER_ROOT/current/public/index.php"
    local CONSOLE_PATH_NEW_RELEASE="php $SERVER_ROOT/releases/$DEPLOYMENT_DIRECTORY/public/index.php"

    local MAINTENANCE_MODE
    MAINTENANCE_MODE=$(select_maintenance_mode)

    info "Enabling maintenance"
    execSSH "$USER" "$DOMAIN" "$CONSOLE_PATH_CURRENT shared:maintenance $MAINTENANCE_MODE"
    execSSH "$USER" "$DOMAIN" "$CONSOLE_PATH_NEW_RELEASE shared:maintenance $MAINTENANCE_MODE"

    if [[ $(type -t "pre_deploy_hook_$ENV") == "function" ]]; then
        "pre_deploy_hook_$ENV" "$USER" "$DOMAIN" "$SERVER_ROOT" "$DEPLOYMENT_DIRECTORY" "$CONSOLE_PATH_NEW_RELEASE"
    fi

    info "Clearing caches"
    execSSH "$USER" "$DOMAIN" "$CONSOLE_PATH_NEW_RELEASE shared:clear-opcc"
    execSSH "$USER" "$DOMAIN" "$CONSOLE_PATH_NEW_RELEASE orm:clear-cache:metadata"
    execSSH "$USER" "$DOMAIN" "$CONSOLE_PATH_NEW_RELEASE orm:clear-cache:query"

    if [[ "$(confirm "Clear result cache?")" == "y" ]]; then
        execSSH "$USER" "$DOMAIN" "$CONSOLE_PATH_NEW_RELEASE orm:clear-cache:result"
    fi

    if [[ "$(confirm "Execute migrations?")" == "y" ]]; then
        execSSH "$USER" "$DOMAIN" "$CONSOLE_PATH_NEW_RELEASE migrations:migrate"
    fi

    if [[ "$(confirm "Execute schema-tool?")" == "y" ]]; then
        execSSH "$USER" "$DOMAIN" "$CONSOLE_PATH_NEW_RELEASE orm:schema-tool:update --dump-sql"
    fi

    # Execute COPS integration commands if enabled
    # This runs after all cache clearing and database operations are completed
    if ! executeCopsIntegration "$ENV" "$USER" "$DOMAIN" "$CONSOLE_PATH_NEW_RELEASE"; then
        critical "Deployment aborted due to COPS integration failure"
        # Disable maintenance mode before exiting
        execSSH "$USER" "$DOMAIN" "$CONSOLE_PATH_NEW_RELEASE shared:maintenance off"
        return 1
    fi

    if [[ $(type -t "post_deploy_hook_$ENV") == "function" ]]; then
        "post_deploy_hook_$ENV" "$USER" "$DOMAIN" "$SERVER_ROOT" "$DEPLOYMENT_DIRECTORY" "$CONSOLE_PATH_NEW_RELEASE"
    fi

    info "Basic Deployment done, run any custom commands now"
    wait_for_keypress

    # disabling maintenance
    execSSH "$USER" "$DOMAIN" "$CONSOLE_PATH_NEW_RELEASE shared:maintenance off"

    # updating current symlink
    execSSH "$USER" "$DOMAIN" "rm $SERVER_ROOT/current"
    execSSH "$USER" "$DOMAIN" "ln -s releases/$DEPLOYMENT_DIRECTORY /var/www/html/current"

    # Handle shared paths symlinking
    handleSharedPaths "$ENV" "$USER" "$DOMAIN" "$SERVER_ROOT" "$DEPLOYMENT_DIRECTORY"

    # final bytecode cache clear
    execSSH "$USER" "$DOMAIN" "$CONSOLE_PATH_NEW_RELEASE shared:clear-opcc"

    if [[ $(type -t "post_deploy_hook_$ENV") == "function" ]]; then
        "done_deploy_hook_$ENV" "$USER" "$DOMAIN" "$SERVER_ROOT" "$DEPLOYMENT_DIRECTORY" "$CONSOLE_PATH_NEW_RELEASE"
    fi

    info "Deployment done"

}

function createSharedPaths() {
    local USER="$1"
    local DOMAIN="$2"
    local SERVER_ROOT="$3"
    local SHARED_DIRECTORIES="$4"
    local SHARED_FILES="$5"

    if [[ -z "$SHARED_DIRECTORIES" && -z "$SHARED_FILES" ]]; then
        return 0
    fi

    info "Creating shared paths..."

    # Create shared directories if they don't exist
    if [[ -n "$SHARED_DIRECTORIES" ]]; then
        IFS=',' read -ra DIRS <<< "$SHARED_DIRECTORIES"
        for dir in "${DIRS[@]}"; do
            if [[ -n "$dir" ]]; then
                local SHARED_DIR_PATH="$SERVER_ROOT/shared/$dir"
                if ! execSSH "$USER" "$DOMAIN" "test -d '$SHARED_DIR_PATH'"; then
                    if execSSH "$USER" "$DOMAIN" "mkdir -p '$SHARED_DIR_PATH'"; then
                        warning "Created missing shared directory: shared/$dir"
                    else
                        critical "Failed to create shared directory: shared/$dir"
                        return 1
                    fi
                fi
            fi
        done
    fi

    # Create shared files if they don't exist
    if [[ -n "$SHARED_FILES" ]]; then
        IFS=',' read -ra FILES <<< "$SHARED_FILES"
        for file in "${FILES[@]}"; do
            if [[ -n "$file" ]]; then
                local SHARED_FILE_PATH="$SERVER_ROOT/shared/$file"
                local SHARED_FILE_DIR
                SHARED_FILE_DIR=$(dirname "$SHARED_FILE_PATH")

                # Create parent directory if needed
                if ! execSSH "$USER" "$DOMAIN" "test -d '$SHARED_FILE_DIR'"; then
                    if ! execSSH "$USER" "$DOMAIN" "mkdir -p '$SHARED_FILE_DIR'"; then
                        critical "Failed to create shared file directory: $(dirname "shared/$file")"
                        return 1
                    fi
                fi

                # Create empty file if it doesn't exist
                if ! execSSH "$USER" "$DOMAIN" "test -f '$SHARED_FILE_PATH'"; then
                    if execSSH "$USER" "$DOMAIN" "touch '$SHARED_FILE_PATH'"; then
                        warning "Created missing shared file: shared/$file"
                    else
                        critical "Failed to create shared file: shared/$file"
                        return 1
                    fi
                fi
            fi
        done
    fi

    return 0
}

function symlinkSharedPaths() {
    local USER="$1"
    local DOMAIN="$2"
    local SERVER_ROOT="$3"
    local DEPLOYMENT_DIRECTORY="$4"
    local SHARED_DIRECTORIES="$5"
    local SHARED_FILES="$6"

    if [[ -z "$SHARED_DIRECTORIES" && -z "$SHARED_FILES" ]]; then
        return 0
    fi

    info "Creating symlinks for shared paths..."

    # Symlink shared directories
    if [[ -n "$SHARED_DIRECTORIES" ]]; then
        IFS=',' read -ra DIRS <<< "$SHARED_DIRECTORIES"
        for dir in "${DIRS[@]}"; do
            if [[ -n "$dir" ]]; then
                local TARGET_PATH="$SERVER_ROOT/current/$dir"
                local SHARED_PATH="$SERVER_ROOT/shared/$dir"

                # Remove existing file/directory at target location
                if ! execSSH "$USER" "$DOMAIN" "rm -rf '$TARGET_PATH'"; then
                    critical "Failed to remove existing path: $dir"
                    return 1
                fi

                # Create symlink
                if ! execSSH "$USER" "$DOMAIN" "ln -sf '$SHARED_PATH' '$TARGET_PATH'"; then
                    critical "Failed to create symlink for shared directory: $dir"
                    return 1
                fi

                info "Symlinked shared directory: $dir"
            fi
        done
    fi

    # Symlink shared files
    if [[ -n "$SHARED_FILES" ]]; then
        IFS=',' read -ra FILES <<< "$SHARED_FILES"
        for file in "${FILES[@]}"; do
            if [[ -n "$file" ]]; then
                local TARGET_PATH="$SERVER_ROOT/current/$file"
                local SHARED_PATH="$SERVER_ROOT/shared/$file"
                local TARGET_DIR
                TARGET_DIR=$(dirname "$TARGET_PATH")

                # Create parent directory if needed
                if ! execSSH "$USER" "$DOMAIN" "mkdir -p '$TARGET_DIR'"; then
                    critical "Failed to create target directory for shared file: $(dirname "$file")"
                    return 1
                fi

                # Remove existing file at target location
                if ! execSSH "$USER" "$DOMAIN" "rm -f '$TARGET_PATH'"; then
                    critical "Failed to remove existing file: $file"
                    return 1
                fi

                # Create symlink
                if ! execSSH "$USER" "$DOMAIN" "ln -sf '$SHARED_PATH' '$TARGET_PATH'"; then
                    critical "Failed to create symlink for shared file: $file"
                    return 1
                fi

                info "Symlinked shared file: $file"
            fi
        done
    fi

    return 0
}

function select_maintenance_mode() {
    local MAINTENANCE_MODE_MAP
    # shellcheck disable=SC2034
    declare -A MAINTENANCE_MODE_MAP=()
    local MAINTENANCE_MODE_ORDER
    # shellcheck disable=SC2034
    declare -a MAINTENANCE_MODE_ORDER=()
    for MODE in "hard" "soft"
    do
        # shellcheck disable=SC2034
        MAINTENANCE_MODE_MAP[$MODE]="$MODE"
        MAINTENANCE_MODE_ORDER+=("$MODE")
    done

    choose_multiple "maintenance mode:" MAINTENANCE_MODE_MAP MAINTENANCE_MODE_ORDER
}

function executeCopsIntegration() {
    local ENV="$1"
    local USER="$2"
    local DOMAIN="$3"
    local CONSOLE_PATH_NEW_RELEASE="$4"

    local COPS_INTEGRATION="false"

    # Extract COPS integration setting from environment configuration
    if [[ -n "${JSON_DEPLOY_ENVS[$ENV]:-}" ]]; then
        # Parse the environment configuration string
        local ENV_CONFIG="${JSON_DEPLOY_ENVS[$ENV]}"

        # Extract COPS integration setting using parameter expansion
        if [[ "$ENV_CONFIG" =~ COPS_INTEGRATION=([^[:space:]]*) ]]; then
            COPS_INTEGRATION="${BASH_REMATCH[1]}"
        fi
    fi

    # Only proceed if COPS integration is enabled
    if [[ "$COPS_INTEGRATION" == "true" ]]; then
        info "Executing COPS integration commands..."
        newline

        # Execute cops:outdated command
        info "Running cops:outdated command..."
        if ! execSSH "$USER" "$DOMAIN" "$CONSOLE_PATH_NEW_RELEASE cops:outdated"; then
            critical "COPS outdated command failed!"
            newline
            warning "This may indicate issues with COPS configuration or connectivity."

            local CONTINUE_DEPLOYMENT
            CONTINUE_DEPLOYMENT=$(confirm -n "Do you want to continue deployment despite COPS command failure?")

            if [[ "$CONTINUE_DEPLOYMENT" != "y" ]]; then
                critical "Deployment aborted due to COPS command failure"
                return 1
            fi

            warning "Continuing deployment despite COPS outdated command failure..."
        else
            info "COPS outdated command completed successfully"
        fi

        # Execute cops:permissions command
        info "Running cops:permissions command..."
        if ! execSSH "$USER" "$DOMAIN" "$CONSOLE_PATH_NEW_RELEASE cops:permissions"; then
            critical "COPS permissions command failed!"
            newline
            warning "This may indicate issues with COPS configuration or permissions."

            local CONTINUE_DEPLOYMENT
            CONTINUE_DEPLOYMENT=$(confirm -n "Do you want to continue deployment despite COPS command failure?")

            if [[ "$CONTINUE_DEPLOYMENT" != "y" ]]; then
                critical "Deployment aborted due to COPS command failure"
                return 1
            fi

            warning "Continuing deployment despite COPS permissions command failure..."
        else
            info "COPS permissions command completed successfully"
        fi

        info "COPS integration commands processing completed"
        newline
    fi

    return 0
}

function handleSharedPaths() {
    local ENV="$1"
    local USER="$2"
    local DOMAIN="$3"
    local SERVER_ROOT="$4"
    local DEPLOYMENT_DIRECTORY="$5"

    local SHARED_DIRECTORIES=""
    local SHARED_FILES=""

    # Extract shared paths from environment configuration
    if [[ -n "${JSON_DEPLOY_ENVS[$ENV]:-}" ]]; then
        # Parse the environment configuration string
        local ENV_CONFIG="${JSON_DEPLOY_ENVS[$ENV]}"

        # Extract shared directories and files using parameter expansion
        if [[ "$ENV_CONFIG" =~ SHARED_DIRECTORIES=([^[:space:]]*) ]]; then
            SHARED_DIRECTORIES="${BASH_REMATCH[1]}"
        fi

        if [[ "$ENV_CONFIG" =~ SHARED_FILES=([^[:space:]]*) ]]; then
            SHARED_FILES="${BASH_REMATCH[1]}"
        fi
    fi

    # Only proceed if there are shared paths configured
    if [[ -n "$SHARED_DIRECTORIES" || -n "$SHARED_FILES" ]]; then
        # Create shared paths if they don't exist
        if ! createSharedPaths "$USER" "$DOMAIN" "$SERVER_ROOT" "$SHARED_DIRECTORIES" "$SHARED_FILES"; then
            critical "Failed to create shared paths"
            return 1
        fi

        # Create symlinks for shared paths
        if ! symlinkSharedPaths "$USER" "$DOMAIN" "$SERVER_ROOT" "$DEPLOYMENT_DIRECTORY" "$SHARED_DIRECTORIES" "$SHARED_FILES"; then
            critical "Failed to create symlinks for shared paths"
            return 1
        fi
    fi

    return 0
}




