services:
  nginx:
    labels:
      com.interligent.dockerplugin.proxy: "nginx"
    container_name: nginx-proxy
    image: nginxproxy/nginx-proxy:1.6
    networks:
      - "frontend-tier"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      DOCKER_HOST: tcp://host.docker.internal:2375
    volumes:
      - "${PLUGIN_MOUNTS_DIR}/ingress/vhosts.d:/etc/nginx/vhost.d:ro"
      - "${PLUGIN_MOUNTS_DIR}/ingress/tls:/etc/nginx/certs:ro"
    logging:
      options:
        max-size: "100M"
        max-file: "4"

  proxy-companion:
    labels:
      com.interligent.dockerplugin.proxy: "companion"
    container_name: proxy-companion
    image: sebastienheyd/self-signed-proxy-companion
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
      DOCKER_HOST: tcp://host.docker.internal:2375
    networks:
      - "frontend-tier"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    volumes:
      - "${PLUGIN_MOUNTS_DIR}/ingress/tls:/etc/nginx/certs:rw"

networks:
  frontend-tier:
    name: proxy

